apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-app
  namespace: prod
  annotations:
spec:
  ingressClassName: nginx
  rules:
  - host: todoprod-34-145-56-240.nip.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: frontend
            port:
              number: 8080
